// Code generated by ent, DO NOT EDIT.

package attendancesync

const (
	// Label holds the string label denoting the attendancesync type in the database.
	Label = "attendance_sync"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLastSyncID holds the string denoting the last_sync_id field in the database.
	FieldLastSyncID = "last_sync_id"
	// EdgeClassPeriod holds the string denoting the classperiod edge name in mutations.
	EdgeClassPeriod = "classPeriod"
	// Table holds the table name of the attendancesync in the database.
	Table = "attendance_syncs"
	// ClassPeriodTable is the table that holds the classPeriod relation/edge.
	ClassPeriodTable = "attendance_syncs"
	// ClassPeriodInverseTable is the table name for the ClassPeriod entity.
	// It exists in this package in order to avoid circular dependency with the "classperiod" package.
	ClassPeriodInverseTable = "class_periods"
	// ClassPeriodColumn is the table column denoting the classPeriod relation/edge.
	ClassPeriodColumn = "class_period_attendance_syncs"
)

// Columns holds all SQL columns for attendancesync fields.
var Columns = []string{
	FieldID,
	FieldLastSyncID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attendance_syncs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"class_period_attendance_syncs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
