// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vmkevv/rigelapi/ent/attendanceday"
	"github.com/vmkevv/rigelapi/ent/predicate"
)

// AttendanceDayDelete is the builder for deleting a AttendanceDay entity.
type AttendanceDayDelete struct {
	config
	hooks    []Hook
	mutation *AttendanceDayMutation
}

// Where appends a list predicates to the AttendanceDayDelete builder.
func (add *AttendanceDayDelete) Where(ps ...predicate.AttendanceDay) *AttendanceDayDelete {
	add.mutation.Where(ps...)
	return add
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (add *AttendanceDayDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, add.sqlExec, add.mutation, add.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (add *AttendanceDayDelete) ExecX(ctx context.Context) int {
	n, err := add.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (add *AttendanceDayDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attendanceday.Table, sqlgraph.NewFieldSpec(attendanceday.FieldID, field.TypeString))
	if ps := add.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, add.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	add.mutation.done = true
	return affected, err
}

// AttendanceDayDeleteOne is the builder for deleting a single AttendanceDay entity.
type AttendanceDayDeleteOne struct {
	add *AttendanceDayDelete
}

// Where appends a list predicates to the AttendanceDayDelete builder.
func (addo *AttendanceDayDeleteOne) Where(ps ...predicate.AttendanceDay) *AttendanceDayDeleteOne {
	addo.add.mutation.Where(ps...)
	return addo
}

// Exec executes the deletion query.
func (addo *AttendanceDayDeleteOne) Exec(ctx context.Context) error {
	n, err := addo.add.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attendanceday.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (addo *AttendanceDayDeleteOne) ExecX(ctx context.Context) {
	if err := addo.Exec(ctx); err != nil {
		panic(err)
	}
}
