// Code generated by ent, DO NOT EDIT.

package school

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/vmkevv/rigelapi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLat), v))
	})
}

// Lon applies equality check predicate on the "lon" field. It's identical to LonEQ.
func Lon(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLon), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLat), v))
	})
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLat), v))
	})
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLat), v...))
	})
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLat), v...))
	})
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLat), v))
	})
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLat), v))
	})
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLat), v))
	})
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLat), v))
	})
}

// LatContains applies the Contains predicate on the "lat" field.
func LatContains(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLat), v))
	})
}

// LatHasPrefix applies the HasPrefix predicate on the "lat" field.
func LatHasPrefix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLat), v))
	})
}

// LatHasSuffix applies the HasSuffix predicate on the "lat" field.
func LatHasSuffix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLat), v))
	})
}

// LatEqualFold applies the EqualFold predicate on the "lat" field.
func LatEqualFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLat), v))
	})
}

// LatContainsFold applies the ContainsFold predicate on the "lat" field.
func LatContainsFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLat), v))
	})
}

// LonEQ applies the EQ predicate on the "lon" field.
func LonEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLon), v))
	})
}

// LonNEQ applies the NEQ predicate on the "lon" field.
func LonNEQ(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLon), v))
	})
}

// LonIn applies the In predicate on the "lon" field.
func LonIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLon), v...))
	})
}

// LonNotIn applies the NotIn predicate on the "lon" field.
func LonNotIn(vs ...string) predicate.School {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLon), v...))
	})
}

// LonGT applies the GT predicate on the "lon" field.
func LonGT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLon), v))
	})
}

// LonGTE applies the GTE predicate on the "lon" field.
func LonGTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLon), v))
	})
}

// LonLT applies the LT predicate on the "lon" field.
func LonLT(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLon), v))
	})
}

// LonLTE applies the LTE predicate on the "lon" field.
func LonLTE(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLon), v))
	})
}

// LonContains applies the Contains predicate on the "lon" field.
func LonContains(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLon), v))
	})
}

// LonHasPrefix applies the HasPrefix predicate on the "lon" field.
func LonHasPrefix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLon), v))
	})
}

// LonHasSuffix applies the HasSuffix predicate on the "lon" field.
func LonHasSuffix(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLon), v))
	})
}

// LonEqualFold applies the EqualFold predicate on the "lon" field.
func LonEqualFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLon), v))
	})
}

// LonContainsFold applies the ContainsFold predicate on the "lon" field.
func LonContainsFold(v string) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLon), v))
	})
}

// HasClasses applies the HasEdge predicate on the "classes" edge.
func HasClasses() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClassesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClassesTable, ClassesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassesWith applies the HasEdge predicate on the "classes" edge with a given conditions (other predicates).
func HasClassesWith(preds ...predicate.Class) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClassesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClassesTable, ClassesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMunicipio applies the HasEdge predicate on the "municipio" edge.
func HasMunicipio() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MunicipioTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MunicipioTable, MunicipioColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMunicipioWith applies the HasEdge predicate on the "municipio" edge with a given conditions (other predicates).
func HasMunicipioWith(preds ...predicate.Municipio) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MunicipioInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MunicipioTable, MunicipioColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.School) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.School) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.School) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		p(s.Not())
	})
}
