// Code generated by ent, DO NOT EDIT.

package apperror

const (
	// Label holds the string label denoting the apperror type in the database.
	Label = "app_error"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCause holds the string denoting the cause field in the database.
	FieldCause = "cause"
	// FieldErrorMsg holds the string denoting the error_msg field in the database.
	FieldErrorMsg = "error_msg"
	// FieldErrorStack holds the string denoting the error_stack field in the database.
	FieldErrorStack = "error_stack"
	// Table holds the table name of the apperror in the database.
	Table = "app_errors"
)

// Columns holds all SQL columns for apperror fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCause,
	FieldErrorMsg,
	FieldErrorStack,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
